"""Default variables used in the analysis"""

UNCERTAINTY_EXPRESSIONS = [
    "almost certain",
    "highly likely",
    "very likely",
    "probable",
    "somewhat likely",
    "possible",
    "uncertain", 
    'somewhat unlikely',
    "unlikely",
    "not likely",
    "doubtful",
    "very unlikely",
    "highly unlikely",
]


PAIRED_MAIN_STATEMENTS = [
    ('Big Ben is located in London.', 'Big Ben is located in Berlin.'),
    ('Great Britain directly borders 0 countries.', 'Great Britain directly borders 2 countries.'),
    ('the Colosseum, a famous landmark in Rome, was originally built as an Amphitheatre.', 'the Colosseum, a famous landmark in Rome, was originally built as an Cathedral.'),
    ('New York is known as the Big Apple.', 'New York is known as the Big Orange.'),
    ('the US president lives in the White House.', 'the UK Prime Minister lives in the White House.'),
    ('Mount Everest is part of the Himalayas mountain range.', 'Mount Everest is part of the Andes mountain range.'),
    ('the Eiffel Tower is made of iron.', 'the Eiffel Tower is made of aluminium.'),
     ('the Statue of Liberty is green.', 'the Statue of Liberty is black.'),
     ('the Great Pyramid of Giza is located in Egypt.',
      'the Sistine Chapel is located in Egypt.'),
     ("before Delhi, Calcutta was India's capital city.",
      "before Delhi, Felfotta was India's capital city."),
     ("water’s chemical formula is H2O.", "carbon monoxide's chemical formula is H2O."),
     ('pH is a measure of the acidity or basicity of a substance.',
      'oG is a measure of the acidity or basicity of a substance.'),
     ('the nearest planet to the sun is Mercury.', 'the nearest planet to the sun is Mars.'),
     ('Antarctica is the only continent without grasslands.', 'Africa is the only continent without grasslands.'),
     ('Neil Armstrong was the first man to set foot on the moon.',
      'Gus Grissom was the first man to set foot on the moon.'),
     ('the largest planet in the solar system is Jupiter.',
      'the largest planet in the solar system is Earth.'),
     ('the branch of science concerned with fossil animals and plants is called Paleontology.',
      'the branch of science concerned with fossil animals and plants is called Serology.'),
     ('the white domestic pigeon symbolizes peace.',
      'the white domestic pigeon symbolizes love.'),
     ('there are more different species of insects than any other type of animal.',
      'there are more different species of mammals than any other type of animal.'),
     ('the moon is the closest astronomical object to the Earth.',
      'the sun is the closest astronomical object to the Earth.'),
     ('the Mona Lisa is a famous painting by Leonardo da Vinci.',
      'the Mona Lisa is a famous painting by Tintoretto.'),
     ('the Scream is the best known painting by Edvard Munch.',
      'the Scream is the best known painting by Jackson Pollock.'),
     ('Andy Warhol became a famous artist in the 1960s for painting soup cans and soap boxes.',
      'Frida Kahlo became a famous artist in the 1960s for painting soup cans and soap boxes.'),
     ('Pablo Picasso was a major force in Cubism.',
      'Pablo Picasso was a major force in Pop Art.'),
     ('the painter Frida Kahlo was Mexican.',
      'the painter Frida Kahlo was Australian.'),
     ('pointillism is the technique of applying paint in small dots.',
      'babillism is the technique of applying paint in small dots.'),
     ('the Renaissance took place in Europe.',
      'the Renaissance took place in Asia.'),
     ('the Renaissance and the Risorgimento are two major historical events in Italy.',
      'the Renaissance and the Risorgimento are two major historical events in the USA.'),
     ('Jackson Pollock is a 20th century artist nicknamed Jack The Dripper.',
      'John Currin is a 20th century artist nicknamed Jack The Dripper.'),
     ('The Thinker is a sculpture by Auguste Rodin.',
      'The Thinker is a sculpture by Barbara Hepworth.'),
]